import Head from 'next/head'
import Image from 'next/image'
import { Footer, Navbar } from '../components'
import Hero from '../components/hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
        <Hero />
      </header>

      <main className=''>
      </main>
      <Footer />
    </>
  )
}
